spring:
  mail:
    host: smtp.gmail.com
    username: netcracker.edu.t2@gmail.com
    password: netcracker234
    port: 465
    protocol: smtps
#For deploy
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/netlibrary_test
    username: postgres
    password: postgres
server:
  port: 8081
