spring:
  mail:
    host: smtp.gmail.com
    username: netcracker.edu.t2@gmail.com
    password: netcracker234
    port: 465
    protocol: smtps
  #For deploy
  datasource:
    url: jdbc:postgresql://db.cources.asem.site/netcracker_library
    username: netcracker_library_user
    password: yu`].tiW5[+.a8l
server:
  port: 8081
