spring:
  mail:
    host: smtp.gmail.com
    username: netcracker.edu.t2@gmail.com
    password: netcracker234
    port: 465
    protocol: smtps
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/Books
    username: postgres
    password: a1b2c3
server:
  port: 8081
