spring:
  mail:
    host: smtp.gmail.com
    username: netcracker.edu.t2@gmail.com
    password: netcracker234
    port: 465
    protocol: smtps
  #For deploy
  datasource:
    url: jdbc:postgresql://localhost/localhost-netcracket
    username: postgres
    password: root
server:
  port: 8081
