spring:
  mail:
    host: smtp.gmail.com
    username: netcracker.edu.t2@gmail.com
    password: netcracker234
    port: 465
    protocol: smtps
#For deploy
 datasource:
   url: ${JDBC_DATABASE_URL}
   username: ${JDBC_DATABASE_USERNAME}
   password: ${JDBC_DATABASE_PASSWORD}
  # datasource:
  #   url: jdbc:postgresql://localhost:5432/test
  #   username: postgres
  #   password: 12345678
server:
  port: 8081
